// personal-website/archive/react-vite-app/src/components/3DCharacter/Character.tsx
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

// This is a placeholder for your 3D character
// You can replace this with your actual 3D model later
const Character = (props: any) => {
  const group = useRef<THREE.Group>(null);
  
  // Simple waving hand animation
  useFrame((state) => {
    if (group.current) {
      // Only animate the hand
      if (group.current.children[0]?.children[1]?.children[0]) {
        const hand = group.current.children[0].children[1].children[0] as THREE.Mesh;
        hand.rotation.z = Math.sin(state.clock.getElapsedTime() * 2) * 0.3;
      }
    }
  });

  return (
    <group {...props} dispose={null}>
      <group ref={group} position={[0, 0, 0]} rotation={[0, 0, 0]}>
        {/* Head */}
        <mesh position={[0, 1.5, 0]} castShadow>
          <sphereGeometry args={[0.5, 32, 32]} />
          <meshStandardMaterial color="#f3b3a6" />
        </mesh>
        
        {/* Body with middle section rotated 90 degrees */}
        <group position={[0, 0.5, 0]}>
          {/* Upper body */}
          <mesh position={[0, 0.25, 0]} castShadow>
            <boxGeometry args={[0.8, 0.5, 0.4]} />
            <meshStandardMaterial color="#fca88e" />
          </mesh>
          
          {/* Middle section - rotated 90 degrees */}
          <mesh position={[0, -0.25, 0]} rotation={[0, 0, Math.PI / 2]} castShadow>
            <boxGeometry args={[0.8, 0.5, 0.4]} />
            <meshStandardMaterial color="#fca88e" />
          </mesh>
          
          {/* Arms */}
          <group position={[0.4, 0, 0]}>
            <mesh position={[0.3, 0, 0]} rotation={[0, 0, -0.5]} castShadow>
              <boxGeometry args={[0.2, 0.7, 0.2]} />
              <meshStandardMaterial color="#f3b3a6" />
            </mesh>
          </group>
          
          <group position={[-0.4, 0, 0]}>
            <mesh position={[-0.3, 0, 0]} rotation={[0, 0, 0.5]} castShadow>
              <boxGeometry args={[0.2, 0.7, 0.2]} />
              <meshStandardMaterial color="#f3b3a6" />
            </mesh>
          </group>
        </group>
        
        {/* Legs */}
        <group position={[0, -0.8, 0]}>
          <mesh position={[0.2, -0.5, 0]} castShadow>
            <boxGeometry args={[0.2, 0.8, 0.2]} />
            <meshStandardMaterial color="#2c3e50" />
          </mesh>
          <mesh position={[-0.2, -0.5, 0]} castShadow>
            <boxGeometry args={[0.2, 0.8, 0.2]} />
            <meshStandardMaterial color="#2c3e50" />
          </mesh>
        </group>
      </group>
    </group>
  );
};

export default Character;

// personal-website/svelte-website/src/lib/components/Character.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Canvas } from '@threlte/core';
	import { T } from '@threlte/core';
	import * as THREE from 'three';
	
	let handRef: THREE.Mesh | null = null;
	let clock = new THREE.Clock();
	let animationId: number;
	
	onMount(() => {
		const animate = () => {
			if (handRef) {
				const elapsedTime = clock.getElapsedTime();
				handRef.rotation.z = Math.sin(elapsedTime * 2) * 0.3;
			}
			animationId = requestAnimationFrame(animate);
		};
		animate();
		
		return () => {
			if (animationId) cancelAnimationFrame(animationId);
		};
	});
</script>

<Canvas>
	<T.Group position={[0, 0, 0]}>
		<!-- Head -->
		<T.Mesh position={[0, 1.5, 0]} castShadow>
			<T.SphereGeometry args={[0.5, 32, 32]} />
			<T.MeshStandardMaterial color="#f3b3a6" />
		</T.Mesh>
		
		<!-- Body -->
		<T.Group position={[0, 0.5, 0]}>
			<!-- Upper body -->
			<T.Mesh position={[0, 0.25, 0]} castShadow>
				<T.BoxGeometry args={[0.8, 0.5, 0.4]} />
				<T.MeshStandardMaterial color="#fca88e" />
			</T.Mesh>
			
			<!-- Middle section - rotated 90 degrees -->
			<T.Mesh position={[0, -0.25, 0]} rotation={[0, 0, Math.PI / 2]} castShadow>
				<T.BoxGeometry args={[0.8, 0.5, 0.4]} />
				<T.MeshStandardMaterial color="#fca88e" />
			</T.Mesh>
			
			<!-- Arms -->
			<T.Group position={[0.4, 0, 0]}>
				<T.Mesh position={[0.3, 0, 0]} rotation={[0, 0, -0.5]} castShadow>
					<T.BoxGeometry args={[0.2, 0.7, 0.2]} />
					<T.MeshStandardMaterial color="#f3b3a6" />
				</T.Mesh>
			</T.Group>
			
			<T.Group position={[-0.4, 0, 0]}>
				<T.Mesh bind:ref={handRef} position={[-0.3, 0, 0]} rotation={[0, 0, 0.5]} castShadow>
					<T.BoxGeometry args={[0.2, 0.7, 0.2]} />
					<T.MeshStandardMaterial color="#f3b3a6" />
				</T.Mesh>
			</T.Group>
		</T.Group>
		
		<!-- Legs -->
		<T.Group position={[0, -0.8, 0]}>
			<T.Mesh position={[0.2, -0.5, 0]} castShadow>
				<T.BoxGeometry args={[0.2, 0.8, 0.2]} />
				<T.MeshStandardMaterial color="#2c3e50" />
			</T.Mesh>
			<T.Mesh position={[-0.2, -0.5, 0]} castShadow>
				<T.BoxGeometry args={[0.2, 0.8, 0.2]} />
				<T.MeshStandardMaterial color="#2c3e50" />
			</T.Mesh>
		</T.Group>
	</T.Group>
</Canvas>
