// personal-website/src/components/UnfinishedGridBackground.tsx
import { useEffect, useRef } from 'react';
import { mountSketchBackground } from '@shared/sketchBackground';

export default function UnfinishedGridBackground() {
	const containerRef = useRef<HTMLDivElement>(null);
	const canvasRef = useRef<HTMLCanvasElement>(null);

	useEffect(() => {
		const container = containerRef.current;
		const canvas = canvasRef.current;
		if (!container || !canvas) return;

		let cleanup: (() => void) | undefined;
		const frame = requestAnimationFrame(() => {
			if (containerRef.current && canvasRef.current) {
				cleanup = mountSketchBackground(canvasRef.current, containerRef.current);
			}
		});

		return () => {
			cancelAnimationFrame(frame);
			cleanup?.();
		};
	}, []);

	return (
		<div className="grid-bg-wrap" ref={containerRef} aria-hidden="true">
			<canvas className="grid-bg" ref={canvasRef} />
		</div>
	);
}

// personal-website/svelte-website/src/lib/components/UnfinishedGridBackground.svelte
<script lang="ts">
	import { tick } from 'svelte';
	import { mountSketchBackground } from '@shared/sketchBackground';

	let canvas: HTMLCanvasElement | undefined;
	let container: HTMLDivElement | undefined;

	$effect(() => {
		const c = canvas;
		const el = container;
		if (!c || !el) return;

		let cleanup: (() => void) | undefined;
		let cancelled = false;

		void tick().then(() => {
			if (cancelled || !canvas || !container) return;
			cleanup = mountSketchBackground(canvas, container);
		});

		return () => {
			cancelled = true;
			cleanup?.();
		};
	});
</script>

<div class="grid-bg-wrap" bind:this={container}>
	<canvas class="grid-bg" bind:this={canvas} aria-hidden="true"></canvas>
</div>

<style>
	.grid-bg-wrap {
		position: fixed;
		inset: 0;
		width: 100vw;
		height: 100vh;
		z-index: 1;
		pointer-events: none;
		overflow: hidden;
		background: var(--background);
	}

	.grid-bg {
		display: block;
		width: 100%;
		height: 100%;
	}
</style>
